using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ECHO.Customization.UI;

[GenerateTypedNameReferences]
public sealed partial class CustomizableAppearanceWindow : DefaultWindow
{
    public CustomizableAppearanceWindow()
    {
        RobustXamlLoader.Load(this);

        ContentsTab.SetTabTitle(0, Loc.GetString("customizable-appearance-markings"));
        ContentsTab.SetTabTitle(1, Loc.GetString("customizable-appearance-misc"));
    }

    public void SetDoll(EntityUid? dollEntity)
    {
        DollView.SetEntity(dollEntity);
    }
}
