using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ECHO.Customization.UI;

[GenerateTypedNameReferences]
public sealed partial class CustomizableAppearanceWindow : DefaultWindow
{
    public CustomizableAppearanceWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
