using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ECHO.Computer.UI;

[GenerateTypedNameReferences]
public sealed partial class ComputerProgramItem : Control
{
    public ComputerProgramItem()
    {
        RobustXamlLoader.Load(this);
    }
}
