using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Client.PDA;
using Content.Client.UserInterface.Controls;
using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._ECHO.Computer.UI;

[GenerateTypedNameReferences]
public sealed partial class ComputerWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly ClientGameTicker _gameTicker;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action? OnCloseItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;

    private EntityUid? _currentProgram;

    public ComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        CloseProgramButton.OnPressed += _ => OnCloseItemPressed?.Invoke();
    }

    public void SetOpenedWindow(Control? fragment, string? title)
    {
        ProgramRoot.Visible = fragment != null;
        ProgramList.Visible = fragment == null;
        ProgramName.SetMarkup(title ?? "");

        if (fragment == null)
            ProgramContainer.RemoveAllChildren();
        else
            ProgramContainer.AddChild(fragment);
    }

    public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
    {
        ProgramList.RemoveAllChildren();

        if (programs.Count == 0)
        {
            ProgramList.AddChild(new Label()
            {
                Text = Loc.GetString("comp-pda-io-no-programs-available"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true
            });

            return;
        }

        var row = CreateProgramListRow();
        var itemCount = 1;
        ProgramList.AddChild(row);

        foreach (var (uid, component) in programs)
        {
            //Create a new row every second program item starting from the first
            if (itemCount % 2 != 0)
            {
                row = CreateProgramListRow();
                ProgramList.AddChild(row);
            }

            var item = new PdaProgramItem();

            if (component.Icon is not null)
                item.Icon.SetFromSpriteSpecifier(component.Icon);

            item.OnPressed += _ =>
            {
                OnProgramItemPressed?.Invoke(uid);
                _currentProgram = uid;
            };

            switch (component.InstallationStatus)
            {
                case InstallationStatus.Cartridge:
                    item.InstallButton.Visible = true;
                    item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                    item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                    break;
                case InstallationStatus.Installed:
                    item.InstallButton.Visible = true;
                    item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                    item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                    break;
            }

            item.ProgramName.Text = Loc.GetString(component.ProgramName);
            item.SetHeight = 20;
            row.AddChild(item);

            itemCount++;
        }

        //Add a filler item to the last row when it only contains one item
        if (itemCount % 2 == 0)
            row.AddChild(new Control() { HorizontalExpand = true });
    }

    private static BoxContainer CreateProgramListRow()
    {
        return new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        TimeLabel.SetMessage(_gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan).ToString("hh\\:mm"));
    }
}
